import { atom } from "recoil";

const studentFormState = atom({
  key: "studentFormState",
  default: {
    program: "",
    acdmc_year: "",
    year_semester: "",
    medium: "",
    sec: "",
    team: "",
    shift: "",
    maj_subj: "",
    first_name: "",
    middle_name: "",
    last_name: "",
    name_nep: "",
    dobn: "",
    phone: "",
    email: "",
    marital_status: "",
    gender: "",
    ethnicity: "",
    caste: "",
    bloodgroup: "",
    citiz_no: "",
    religion: "",
    nationality: "Nepalese",
    province: "",
    district: "",
    municipality: "",
    wardno: "",
    add_nep: "",
    tempadd: "",
    sms_mob_no: "",
    dorm_facility: "",
    bus_facility: "",
    father_name: "",
    fath_ph: "",
    father_qualification: "",
    mother_name: "",
    moth_ph: "",
    mother_qualification: "",
  },
});

export default studentFormState;
