import { atom } from "recoil";

const studentFormState = atom({
  key: "studentFormState",
  default: {
    program: "",
    acdmc_year: 0,
    year_semester: 0,
    medium: 0,
    sec: 0,
    team: 0,
    shift: 0,
    maj_subj: 0,
    first_name: "",
    middle_name: "",
    last_name: "",
    name_nep: "",
    dobn: "",
    phone: "",
    email: "",
    marital_status: 0,
    gender: 0,
    sub_caste: 0,
    caste: 1,
    bloodgroup: "",
    citiz_no: "",
    religion: "",
    nationality: "Nepalese",
    province: 1,
    district: 0,
    municipality: 0,
    wardno: 0,
    add_nep: "",
    tempadd: "",
    sms_mob_no: "",
    dorm_facility: false,
    bus_facility: false,
    father_name: "",
    fath_ph: "",
    father_qualification: 0,
    mother_name: "",
    moth_ph: "",
    mother_qualification: 0,
  },
});

export default studentFormState;
